name: and

volumes:
  world:

services:
  server:
    image: docker.pool.net.eu.org/and-server/server
    build: dedicated-server/
    init: true
    cpus: 3
    volumes:
      - world:/mnt
    ports:
      - 39781:25565
      - 42279:42279/udp
