hash-format = "sha256"

[[files]]
file = "compose.yml"

[[files]]
file = "mods/ae2.pw.toml"
metafile = true

[[files]]
file = "mods/amethyst-gravity-reattracted.pw.toml"
metafile = true

[[files]]
file = "mods/animal_feeding_trough.pw.toml"
metafile = true

[[files]]
file = "mods/animorphs.pw.toml"
metafile = true

[[files]]
file = "mods/apugli.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/arwa-1.0.0.jar"

[[files]]
file = "mods/automobility.pw.toml"
metafile = true

[[files]]
file = "mods/autoslabs.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/block-o-morph.pw.toml"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
metafile = true

[[files]]
file = "mods/caves__canyons.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/critters-and-companions.pw.toml"
metafile = true

[[files]]
file = "mods/eggolib.pw.toml"
metafile = true

[[files]]
file = "mods/ensculked-0.1.4-eazs+1.20.1.jar"

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/forgiving-void.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-library-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-quests-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-teams-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/gravity-api-fork.pw.toml"
metafile = true

[[files]]
file = "mods/hex-casting.pw.toml"
metafile = true

[[files]]
file = "mods/immersiveportals.pw.toml"
metafile = true

[[files]]
file = "mods/impenduits.pw.toml"
metafile = true

[[files]]
file = "mods/inline.pw.toml"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
metafile = true

[[files]]
file = "mods/mage-flame.pw.toml"
metafile = true

[[files]]
file = "mods/mermod.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/more-crafting-tables-lieonlion.pw.toml"
metafile = true

[[files]]
file = "mods/origins.pw.toml"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/paucal.pw.toml"
metafile = true

[[files]]
file = "mods/pockets.pw.toml"
metafile = true

[[files]]
file = "mods/pooltoy-origin-0.3.1.jar"

[[files]]
file = "mods/quad.pw.toml"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
metafile = true

[[files]]
file = "mods/storagent.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/vowels-1.0.0+1.20.1.jar"

[[files]]
file = "mods/weeping-angels.pw.toml"
metafile = true
