hash-format = "sha256"

[[files]]
file = "compose.yml"

[[files]]
file = "config/fabric_loader_dependencies.json"

[[files]]
file = "config/vowels-packwiz.json"

[[files]]
file = "icon.png"

[[files]]
file = "mods/ad-astra.pw.toml"
metafile = true

[[files]]
file = "mods/ae2-emi-crafting.pw.toml"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
metafile = true

[[files]]
file = "mods/amethyst-gravity-reattracted.pw.toml"
metafile = true

[[files]]
file = "mods/animal_feeding_trough.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/apugli.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/armorpoints.pw.toml"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
metafile = true

[[files]]
file = "mods/arwa-1.0.0.jar"

[[files]]
file = "mods/auth-me.pw.toml"
metafile = true

[[files]]
file = "mods/automobility.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/block-o-morph.pw.toml"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
metafile = true

[[files]]
file = "mods/bountiful.pw.toml"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
metafile = true

[[files]]
file = "mods/caves__canyons.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
metafile = true

[[files]]
file = "mods/chunk-loaders.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/complex-hex.pw.toml"
metafile = true

[[files]]
file = "mods/coolrain.pw.toml"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/critters-and-companions.pw.toml"
metafile = true

[[files]]
file = "mods/dimensional-tears.pw.toml"
metafile = true

[[files]]
file = "mods/dimensionaldoors.pw.toml"
metafile = true

[[files]]
file = "mods/ducky-periphs.pw.toml"
metafile = true

[[files]]
file = "mods/eggolib.pw.toml"
metafile = true

[[files]]
file = "mods/emi-create-schematics.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/ensculked-0.1.4-pre.1+1.20.1+eazs.jar"

[[files]]
file = "mods/explosive-enhancement.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/figura-0.1.5+1.20.1-fabric-mc.jar"

[[files]]
file = "mods/flux-network-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/forgiving-void.pw.toml"
metafile = true

[[files]]
file = "mods/friendly-phantoms.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-library-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-quests-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-teams-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/gravity-api-fork.pw.toml"
metafile = true

[[files]]
file = "mods/hex-casting.pw.toml"
metafile = true

[[files]]
file = "mods/hex-machina.pw.toml"
metafile = true

[[files]]
file = "mods/hexal-fabric-1.20.1-0.3.0-3-skyevg-unofficial.jar"

[[files]]
file = "mods/hexcassettes.pw.toml"
metafile = true

[[files]]
file = "mods/hexcellular.pw.toml"
metafile = true

[[files]]
file = "mods/hexchanting.pw.toml"
metafile = true

[[files]]
file = "mods/hexdebug.pw.toml"
metafile = true

[[files]]
file = "mods/hexical.pw.toml"
metafile = true

[[files]]
file = "mods/hextweaks.pw.toml"
metafile = true

[[files]]
file = "mods/hexweb.pw.toml"
metafile = true

[[files]]
file = "mods/immersiveportals.pw.toml"
metafile = true

[[files]]
file = "mods/impenduits.pw.toml"
metafile = true

[[files]]
file = "mods/impersonate.pw.toml"
metafile = true

[[files]]
file = "mods/inline.pw.toml"
metafile = true

[[files]]
file = "mods/inventorio.pw.toml"
metafile = true

[[files]]
file = "mods/invview.pw.toml"
metafile = true

[[files]]
file = "mods/ioticblocks.pw.toml"
metafile = true

[[files]]
file = "mods/kambrik.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/mage-flame.pw.toml"
metafile = true

[[files]]
file = "mods/mindweaver-0.1-1.20.1-fabric (1).jar"

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/more-crafting-tables-lieonlion.pw.toml"
metafile = true

[[files]]
file = "mods/moreiotas.pw.toml"
metafile = true

[[files]]
file = "mods/oneironaut-fabric-1.20.1-0.5.0.jar"

[[files]]
file = "mods/open-loader.pw.toml"
metafile = true

[[files]]
file = "mods/origins.pw.toml"
metafile = true

[[files]]
file = "mods/overevaluate-1.0.0.jar"

[[files]]
file = "mods/owo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/paucal.pw.toml"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
metafile = true

[[files]]
file = "mods/pick-your-poison.pw.toml"
metafile = true

[[files]]
file = "mods/pockets.pw.toml"
metafile = true

[[files]]
file = "mods/pooltoy-origin-0.3.3.jar"

[[files]]
file = "mods/powah.pw.toml"
metafile = true

[[files]]
file = "mods/quad.pw.toml"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
metafile = true

[[files]]
file = "mods/satin-api.pw.toml"
metafile = true

[[files]]
file = "mods/sdlink.pw.toml"
metafile = true

[[files]]
file = "mods/seamless.pw.toml"
metafile = true

[[files]]
file = "mods/storagent.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/sushi-bar.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/universal-perms.pw.toml"
metafile = true

[[files]]
file = "mods/vanish.pw.toml"
metafile = true

[[files]]
file = "mods/vowels-1.0.0+1.20.1.jar"

[[files]]
file = "mods/weeping-angels.pw.toml"
metafile = true

[[files]]
file = "mods/xaero-zoomout.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "unsup.toml"
