name = "And Server"
author = "PoolloverNathan"
version = "0.0.1-pre.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
unsup = "1.0.2"

[options]
no-internal-hashes = true
